### ISSUE TITLE
Plugin stuck on connecting

### ISSUE THREAD

**Issue by Haximaxi** [Ertego/gog-galaxy-discord#1]
First of all thanks for creating this plug in

I do how ever have an issue, when i follow your instructions to the letter the plugin restarts discord yes but nothing happens after that and it is kinda stuck on "Starting.." 
![image](https://user-images.githubusercontent.com/57035855/67618919-b22f4000-f7f5-11e9-8c04-e0dbb3f8bd92.png)

And after that it shows "Failed to start, Retry" 
![image](https://user-images.githubusercontent.com/57035855/67618933-dab73a00-f7f5-11e9-8e41-e13829e39fb1.png)

And all i can do is repeat the process with the same result, i have both galaxy and discord open and updated to the latest versions

**Comment by lele-blue** [comment]
There's currently a bug in the integration that prevents it from working if you have no game installed through discord. (There are some free ones in the discord store)
If you already have a game installed or if the bug persists, can you please attach the logfile of the plugin to this issue?

**Comment by Haximaxi** [comment]
Thanks for the fast reply

I cant seem to find the store anywhere in the app anymore,  from what i gather the store has now been rolled into nitro feature and there is no "free games" to collect unless you subscribe to nitro, so i am afraid i cant help you out further

**Comment by Haximaxi** [comment]
I have tried several times with a game installed
![image](https://user-images.githubusercontent.com/57035855/67621096-8e77f400-f80d-11e9-8bc0-eb293df7053e.png)
but it remains stuck even after 30min+
![image](https://user-images.githubusercontent.com/57035855/67621107-a0599700-f80d-11e9-96f3-225179315f46.png)
Were can i find the the logfile for the plugin?

**Comment by lele-blue** [comment]
They're in C:/ProgramData/GOG.com/Galaxy/logs

**Comment by Haximaxi** [comment]
Here it is

[plugin-discord-ce69028e-a7e4-462a-96d8-468259c298e2.log](https://github.com/Ertego/gog-galaxy-discord/files/3774927/plugin-discord-ce69028e-a7e4-462a-96d8-468259c298e2.log)

**Comment by lele-blue** [comment]
Ok, that seems bad. Really bad if i'm right.
I'll try to explain what i think happened (I might be wrong though, this definitely needs more investigation):
Based on your logfile it seems as if the command 'Runtime.Evaluate', which is used to execute javascript in the discord client, is unsupported by your discord client. That is strange since it's a default feature of electron (the framework used by discord).
I think this might be discords reaction to this integration as they probably don't want their platform being used by gog galaxy, but it's just a guess and it needs more investigation.
I'll try to find a fix for it, but that seems like a major thing. I'll keep this issue updated about it.

tl:dr: Discord might be taking action against my integration and i need to investigate it :/

**Comment by tylerbrawl** [comment]
I went ahead and submitted a pull request for this at #2.

**Comment by bdemirel** [comment]
I have tried the new version, however, I'm still getting an error
![image](https://user-images.githubusercontent.com/8352631/70147602-862c9780-169c-11ea-9ce8-c84dfa661d60.png)

Do i still need to have a game installed through Discord? Here's the log file, if needed:
[plugin-discord-ce69028e-a7e4-462a-96d8-468259c298e2.log](https://github.com/Ertego/gog-galaxy-discord/files/3922114/plugin-discord-ce69028e-a7e4-462a-96d8-468259c298e2.log)

**Comment by tylerbrawl** [comment]
That is correct. Once the Rockstar plugin is in a stable state, I plan on creating a new Discord plugin. This new plugin will use the actual Discord API, rather than JavaScript exploits, to get information regarding the user. It will likely take some time before this gets released in any usable state, but the general idea is there. 

For now, however, having a game is required. The "fix" I made did nothing more than restore the original functionality of the plugin.

**Comment by bdemirel** [comment]
Well, I have now tried, after downloading Paladins from Discord, and the plug-in is still crushing. Seems I'll have to wait till later.
Also, I'd love to help, if there's anything I can do for the API version!

**Comment by tylerbrawl** [comment]
You are not alone on this one. After testing it myself, I am also getting this error. I will see if I can fix it quickly, but for all intents and purposes, this version of the plugin should be considered deprecated.

**Comment by tylerbrawl** [comment]
The attached build is working for me, and hopefully it fixes your issues, too. If you would like a very early copy of the API version of the plugin, then I can submit that for you, also. Just know that the API version is currently not as feature-complete as this version, but it shows promise.

[**Discord.zip**](https://github.com/Ertego/gog-galaxy-discord/files/3924293/Discord.zip)

**Comment by bdemirel** [comment]
This one, did indeed, work for me, even though i had uninstalled Paladins. I still have that in my Discord library tho, however GOG cannot see that at all.
Tbf, my goal was never to add the games from Discord, more than that, I wanted to get the friend recommendations, and atm, I have no idea if it works or not 😅 

As for the API version, I'd love to see that. More to be able to check it out and see if I can help, than making any use out of it.

**Comment by tylerbrawl** [comment]
Honestly, I cannot tell whether friend recommendations even work on Galaxy 2.0 either, since I do not have many friends across accounts that have access to the beta. (As a side note, would you be willing to help me test social features for my Rockstar plugin? You will need a Social Club account, but it does not need to have any games on it. Message me on Discord (my username there is Tylerbrawl#1012) with your Social Club username if you are interested!)

Attached to this post is the current iteration of the planned API version. It is *very* basic right now (it only supports getting the user's username and discriminator), but when finished, it will prove to be far more expandable than the current plugin. Make sure to disconnect from the current Discord plugin before installing this version.

@Ertego - Feel free to mark this issue as "closed," unless @Haximaxi is having problems with this new version of the plugin.

[**Discord-API.zip**](https://github.com/Ertego/gog-galaxy-discord/files/3927035/Discord-API.zip)

**Comment by epsimatic** [comment]
> There's currently a bug in the integration that prevents it from working if you have no game installed through discord. (There are some free ones in the discord store)

I'm having the same issue and I don't see a «discord store» or anything like that in Discord. Is it OS specific? I'm using Mac OS latest

**Comment by lele-blue** [comment]
> I'm having the same issue and I don't see a «discord store» or anything like that in Discord. Is it OS specific? I'm using Mac OS latest

Discord more or less shut down their whole store, which makes this plugin kind of redundant. I'll maybe update it to no longer be affected of this bug

**Comment by SlipSlot** [comment]
> > Discord more or less shut down their whole store, which makes this plugin kind of redundant. I'll maybe update it to no longer be affected of this bug

A lot of us still have large purchased, freebie, nitro and free-to-play titles in our libraries that are still playable, so while it probably has less demand now, it would still be useful for a fair portion of us (myself included).

I've installed a game via the client in the default destination and tried running both application as administrator and still the connection just loops and never links to Discord.

I hope you take another took at some tweaks to give it a higher success rate <3

**Comment by SlipSlot** [comment]
> The attached build is working for me, and hopefully it fixes your issues, too. If you would like a very early copy of the API version of the plugin, then I can submit that for you, also. Just know that the API version is currently not as feature-complete as this version, but it shows promise.

I gave this a try and although it seems to connect (somewhere along the line), during the Discord restart it seems to loose its link and claims to be offline, with the option to 'retry', clicking this does nothing, disconnecting and attempting to reconnect presents the same issue https://prnt.sc/robwmt

> Attached to this post is the current iteration of the planned API version. It is _very_ basic right now (it only supports getting the user's username and discriminator), but when finished, it will prove to be far more expandable than the current plugin. Make sure to disconnect from the current Discord plugin before installing this version.

I gave your API version a shot and it connected I'm guessing successfully? Hard to know when GOG doesn't give any indication as to what account it's pulling data from. Obviously its not showing any game or friend data, but at least we're over the connection hurdle!

Would be very interested to see how this plugin develops. Any progress in the last 4 months?

**Comment by tylerbrawl** [comment]
I haven't been working on it as of late. If Discord really did close down their entire store, then the only real utility of a plugin for it for most people would be the social features (i.e., the user's friends list, chat, etc.). Unfortunately, Discord has not exposed this portion of the API to all users as of yet (and they seem to be taking their sweet time to do so, since it has been months since I last checked).

For a reference, you can visit https://discordapp.com/developers/docs/topics/oauth2#shared-resources-oauth2-scopes and look at the required scopes. Specifically, ``relationships.read`` is still set to "whitelist only," and I don't believe that they are taking additional applications for this anytime soon.

**Comment by lele-blue** [comment]
I also don't think that these scopes will be made public anytime soon, which is why i chose the "inject js into the client" method since it is working at the moment

**Comment by AstroPhysX** [comment]
Hello, I'm new to gog 2.0 and I was wondering if there is anyway to have your discord friend-list along with their status of what game they're playing to show on the gog 2.0 friend-list? I tried yalls integration but I couldn't get it to work. Is there a cheeky way of doing this?

**Comment by lele-blue** [comment]
@triplethreat999 the plugin is more a poc than anything well tested and working. The steps in the readme *should* get it to work, but even then it's mostly trial and error.
I might put additional work in this, but since discord closed their game store I'm not sure if it's worth the effort

**Comment by AstroPhysX** [comment]
@Ertego yeah I understand you perfectly. It seems like its not an easy thing to pull off. I just hope that gog 2.0 eventually implements a system that will allow us to have all our discord friends as well as their status shown within gog. I personally don't have any games from discord so the integration is not as important to me as for example battle.net or even steam. But regardless thank you for your quick response, Cheers.
