### ISSUE TITLE
Release 0.1.1

### ISSUE THREAD

**Issue by BilliAlpha** [Ertego/gog-galaxy-discord#8]
Would it be possible to build a release zip of version 0.1.1 ?

**Comment by lele-blue** [comment]
That version should be available from the releases section of the repo

**Comment by BilliAlpha** [comment]
Unless I'm mistaken there isn't a release for version 0.1.1

**Comment by lele-blue** [comment]
Sorry for that, I didn't realize this issue was for the discord integration.
Since I am no longer developing this plugin since discord shut down the storefront, I didn't bundle the release into a working zipfile.
If you are still actively using the integration, you can use the existing zipfile and replace the discord.py file with the one from the master branch

**Comment by BilliAlpha** [comment]
I just discovered the integration and just wanted to give it a try.
Is there still no API to lookup a user friends ?
It would remove the need of hooking into the client directly

**Comment by lele-blue** [comment]
There is an API, but it's not available via OAuth, but only for User Accounts.
To access it, a selfbot would be required, which would violate the discord TOS.

**Comment by BilliAlpha** [comment]
Understood, thanks anyway.
